FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY target/Spring-Boot-Demo-Project-0.0.1-SNAPSHOT.jar Spring-Boot-Demo-Project-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Spring-Boot-Demo-Project-0.0.1-SNAPSHOT.jar"]